### ISSUE TITLE
选择器不支持:hidden :visible

### ISSUE THREAD

**Issue by Arronlong** [LuckyHH/WebSpider#2]
RT

错误实例：
`
{ "state": false, "time": "2018-11-15T13:36:05.022Z", "data": "Error: SyntaxError: unmatched pseudo-class :visible" }
`

**Comment by LuckyHH** [comment]
@Arronlong 

> RT
> 
> 错误实例：
> `{ "state": false, "time": "2018-11-15T13:36:05.022Z", "data": "Error: SyntaxError: unmatched pseudo-class :visible" }`

在冒号前加//试试
